board_games = [
  { name: "Catan", price_cents: 34.99, condition: "mint" },
  { name: "Ticket to Ride", price_cents: 12.50, condition: "good" },
  { name: "Pandemic", price_cents: 27.00, condition: "excellent" },
  { name: "Carcassonne", price_cents: 8.75, condition: "as_is" },
  { name: "Dominion", price_cents: 45.00, condition: "mint" },
  { name: "Azul", price_cents: 19.99, condition: "good" },
  { name: "7 Wonders", price_cents: 38.50, condition: "excellent" },
  { name: "Splendor", price_cents: 22.00, condition: "mint" },
  { name: "Wingspan", price_cents: 49.99, condition: "good" },
  { name: "Codenames", price_cents: 11.25, condition: "as_is" },
  { name: "Betrayal at House on the Hill", price_cents: 33.00, condition: "excellent" },
  { name: "Gloomhaven", price_cents: 47.50, condition: "mint" },
  { name: "Terraforming Mars", price_cents: 41.00, condition: "good" },
  { name: "Dixit", price_cents: 16.75, condition: "excellent" },
  { name: "Agricola", price_cents: 29.99, condition: "as_is" },
  { name: "Power Grid", price_cents: 36.00, condition: "mint" },
  { name: "Lords of Waterdeep", price_cents: 23.50, condition: "good" },
  { name: "Arkham Horror", price_cents: 44.00, condition: "excellent" },
  { name: "King of Tokyo", price_cents: 18.25, condition: "as_is" },
  { name: "Smallworld", price_cents: 31.00, condition: "mint" },
  { name: "Race for the Galaxy", price_cents: 14.99, condition: "good" },
  { name: "Forbidden Island", price_cents: 9.50, condition: "as_is" },
  { name: "Pandemic Legacy Season 1", price_cents: 48.00, condition: "excellent" },
  { name: "Through the Ages", price_cents: 43.75, condition: "mint" },
  { name: "Istanbul", price_cents: 26.00, condition: "good" },
  { name: "Battlestar Galactica", price_cents: 39.99, condition: "as_is" },
  { name: "Dead of Winter", price_cents: 35.50, condition: "excellent" },
  { name: "Viticulture", price_cents: 46.00, condition: "mint" },
  { name: "Coup", price_cents: 7.25, condition: "good" },
  { name: "Sheriff of Nottingham", price_cents: 21.00, condition: "as_is" },
  { name: "Tokaido", price_cents: 17.50, condition: "excellent" },
  { name: "Robinson Crusoe", price_cents: 40.00, condition: "mint" },
  { name: "Mysterium", price_cents: 28.75, condition: "good" },
  { name: "Twilight Struggle", price_cents: 37.00, condition: "as_is" },
  { name: "Concordia", price_cents: 32.50, condition: "excellent" },
  { name: "Pandemic Iberia", price_cents: 24.99, condition: "mint" },
  { name: "Spirit Island", price_cents: 50.00, condition: "good" },
  { name: "Everdell", price_cents: 30.25, condition: "excellent" },
  { name: "The Resistance", price_cents: 6.50, condition: "mint" },
  { name: "Bruges", price_cents: 20.00, condition: "good" },
  { name: "Blood Rage", price_cents: 45.75, condition: "as_is" },
  { name: "Village", price_cents: 15.00, condition: "excellent" },
  { name: "Hive", price_cents: 13.50, condition: "mint" },
  { name: "Quacks of Quedlinburg", price_cents: 25.50, condition: "as_is" },
  { name: "Mansions of Madness", price_cents: 47.00, condition: "mint" },
  { name: "Patchwork", price_cents: 10.75, condition: "good" },
  { name: "Great Western Trail", price_cents: 44.50, condition: "as_is" }
]

Game.insert_all(board_games)
